[package]
name = "client"
version = "0.0.0"
edition = "2021"

[dependencies]
protocol = {path = "../protocol"}
borsh = "0.9"
solana-client = "=1.11.5"
solana-sdk = "=1.11.5"
solana-program = "=1.11.5"
rand = "0.8.5"
