[package]
name = "program"
version = "0.0.0"
edition = "2021"

[dependencies]
protocol = {path = "../protocol"}
borsh = "0.9"
solana-program = "=1.11.5"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []
